# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

stream:

zha:
  enable_quirks: true
  custom_quirks_path: /mnt/dietpi_userdata/homeassistant/zha_quirks

light:
  - platform: group
    unique_id: Dining_Lights
    name: 'Dining Table Lights'
    entities:
      - light.living_room_spot_window
      - light.living_room_spot_door
      - light.living_room_spot_middle

sensor:

# --- TEMPLATE SENSORS ---
template:
  - sensor:
      - name: "PV energy day"
        unique_id: pv_eday
        state: "{{ state_attr('sensor.inverter_45a_horsell', 'eday') | float(0) }}"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing

      - name: "Gas Consumption Today (Volume)"
        unique_id: gas_consumption_today_m3
        state: "{{ states('sensor.gas_consumption_today') | float(0) * 0.091 }}"
        unit_of_measurement: "m³"
        device_class: gas
        state_class: total_increasing

      - name: "Washing Machine State"
        unique_id: washing_machine_state
        state: >
          {% set s = states('sensor.washing_machine_state') %}
          {% set p = states('sensor.washing_machine_power') %}
          {% if p == 'unavailable' %}
            unavailable
          {% else %}
            {% set p = p | int %}
            {% if p == 0 %} off
            {% elif p <= 2 %} standby
            {% elif p > 2 %} run
            {% else %} {{ s }}
            {% endif %}
          {% endif %}

      - name: "Dishwasher State"
        unique_id: dishwasher_state
        state: >
          {% set s = states('sensor.dishwasher_state') %}
          {% set p = states('sensor.dishwasher_power') %}
          {% if p == 'unavailable' %}
            unavailable
          {% else %}
            {% set p = p | int %}
            {% if p == 0 %} off
            {% elif p <= 7 %} standby
            {% elif p > 7 %} run
            {% else %} {{ s }}
            {% endif %}
          {% endif %}

  - cover:
    - device_class: shade
      open_cover:
      - target:
          entity_id:
          - cover.wall
        action: cover.open_cover
      close_cover:
      - target:
          entity_id:
          - cover.wall
        action: cover.close_cover
      default_entity_id: cover.wall_blind
      name: Wall Blind

  - cover:
    - device_class: shade
      open_cover:
      - target:
          entity_id:
          - cover.middle
        action: cover.open_cover
      close_cover:
      - target:
          entity_id:
          - cover.middle
        action: cover.close_cover
      default_entity_id: cover.middle_blind
      name: Middle Blind

  - cover:
    - device_class: shade
      open_cover:
      - target:
          entity_id:
          - cover.door
        action: cover.open_cover
      close_cover:
      - target:
          entity_id:
          - cover.door
        action: cover.close_cover
      default_entity_id: cover.door_blind
      name: Door Blind

  - cover:
    - device_class: shade
      open_cover:
      - target:
          entity_id:
          - cover.kitchen
        action: cover.open_cover
      close_cover:
      - target:
          entity_id:
          - cover.kitchen
        action: cover.close_cover
      default_entity_id: cover.kitchen_blind
      name: Kitchen Blind


# --- INTEGRATION SENSORS ---
sensor:
  - platform: integration
    source: sensor.pv_excess
    name: excess_solar
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.washing_machine_power
    name: washing_machine_eusage
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.dishwasher_power
    name: dishwasher_eusage
    unit_prefix: k
    round: 2

  #- platform: template
  #  sensors:
  #    dishwasher_state:
  #      friendly_name: Dishwasher State
  #      value_template: >
  #        {% set s = states('sensor.dishwasher_state') %}
  #        {% set p = states('sensor.dishwasher_power') %}
  #        {% if p == 'unavailable' %}
  #          unavailable
  #        {% else %}
  #          {% set p = p | int %}
  #          {% if p == 0 %} off
  #          {% elif p <= 7 %} standby
  #          {% elif p > 7 %} run
  #          {% else %} {{ s }}
  #          {% endif %}
  #        {% endif %}

command_line:
  - sensor:
      name: "bin_collection"
      unique_id: "binday"
      command: "/mnt/dietpi_userdata/homeassistant/scripts/BinDay/venv/bin/python /mnt/dietpi_userdata/homeassistant/scripts/BinDay/binday.py"
      json_attributes:
        - "Rubbish"
        - "Food waste"
        - "Recycling"
        - "next_colour"
        - "status"
        - "days_until"
      value_template: "{{ value_json.next_bin_day }}"
      scan_interval: 43200
