# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

stream:

zha:
  enable_quirks: true
  custom_quirks_path: /mnt/dietpi_userdata/homeassistant/zha_quirks

# --- TEMPLATE SENSORS ---
template:
  - sensor:
      - name: "Washing Machine State"
        unique_id: washing_machine_state
        state: >
          {% set s = states('sensor.washing_machine_state') %}
          {% set p = states('sensor.washing_machine_power') %}
          {% if p == 'unavailable' %}
            unavailable
          {% else %}
            {% set p = p | int %}
            {% if p == 0 %} off
            {% elif p <= 2 %} standby
            {% elif p > 2 %} run
            {% else %} {{ s }}
            {% endif %}
          {% endif %}

      - name: "Dishwasher State"
        unique_id: dishwasher_state
        state: >
          {% set s = states('sensor.dishwasher_state') %}
          {% set p = states('sensor.dishwasher_power') %}
          {% if p == 'unavailable' %}
            unavailable
          {% else %}
            {% set p = p | int %}
            {% if p == 0 %} off
            {% elif p <= 7 %} standby
            {% elif p > 7 %} run
            {% else %} {{ s }}
            {% endif %}
          {% endif %}


# --- INTEGRATION SENSORS ---
sensor:
  - platform: integration
    source: sensor.washing_machine_power
    name: washing_machine_eusage
    unit_prefix: k
    round: 2

  - platform: integration
    source: sensor.dishwasher_power
    name: dishwasher_eusage
    unit_prefix: k
    round: 2

command_line:
  - sensor:
      name: "bin_collection"
      unique_id: "binday"
      command: "/mnt/dietpi_userdata/homeassistant/scripts/BinDay/venv/bin/python /mnt/dietpi_userdata/homeassistant/scripts/BinDay/binday.py"
      json_attributes:
        - "Rubbish"
        - "Food waste"
        - "Recycling"
        - "next_colour"
        - "status"
        - "days_until"
      value_template: "{{ value_json.next_bin_day }}"
      scan_interval: 43200
